SET SQLBLANKLINES ON
CREATE TABLE DANIA 
(
  ID_DANIA NUMBER(3, 0) NOT NULL 
, NAZWA VARCHAR2(30 BYTE) NOT NULL 
, OPIS VARCHAR2(200 BYTE) 
, CENA NUMBER(5, 2) NOT NULL 
, DOSTEPNOSC NUMBER(3, 0) DEFAULT 0 NOT NULL 
, CONSTRAINT DANIA_PK PRIMARY KEY 
  (
    ID_DANIA 
  )
  ENABLE 
);

CREATE TABLE SL_BANKI 
(
  ID_BANKU NUMBER(3, 0) NOT NULL 
, NAZWA VARCHAR2(50 BYTE) NOT NULL 
, CONSTRAINT SL_BANKI_PK PRIMARY KEY 
  (
    ID_BANKU 
  )
  ENABLE 
) 
ORGANIZATION INDEX 
PCTTHRESHOLD 50;

CREATE TABLE SL_JEDNOSTKI 
(
  ID_JEDNOSTKI NUMBER(2, 0) NOT NULL 
, NAZWA VARCHAR2(30 BYTE) NOT NULL 
, SKROT VARCHAR2(10 BYTE) NOT NULL 
, CONSTRAINT SL_JEDNOSTKI_PK PRIMARY KEY 
  (
    ID_JEDNOSTKI 
  )
  ENABLE 
) 
ORGANIZATION INDEX 
PCTTHRESHOLD 50;

CREATE TABLE SL_KATEGORIE_PODATKOWE 
(
  ID_KATEGORII NUMBER(2, 0) NOT NULL 
, NAZWA VARCHAR2(30 BYTE) NOT NULL 
, OPODATKOWANIE NUMBER(2, 0) NOT NULL 
, CONSTRAINT SL_KATEGORIE_PK PRIMARY KEY 
  (
    ID_KATEGORII 
  )
  ENABLE 
) 
ORGANIZATION INDEX 
PCTTHRESHOLD 50;

CREATE TABLE SL_STATUSY_ZAMOWIEN 
(
  ID_STATUSU NUMBER(2, 0) NOT NULL 
, NAZWA VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT SL_STATUSY_ZAMOWIEN_PK PRIMARY KEY 
  (
    ID_STATUSU 
  )
  ENABLE 
) 
ORGANIZATION INDEX 
PCTTHRESHOLD 50;

CREATE TABLE KONTRAHENCI 
(
  ID_KONTRAHENTA NUMBER(5, 0) NOT NULL 
, IMIE VARCHAR2(20 BYTE) 
, NAZWISKO VARCHAR2(40 BYTE) 
, NAZWA VARCHAR2(50 BYTE) 
, NIP CHAR(13 BYTE) 
, MAIL VARCHAR2(40 BYTE) NOT NULL 
, ADRES VARCHAR2(150 BYTE) NOT NULL 
, TELEFON VARCHAR2(15 BYTE) NOT NULL 
, ID_BANKU NUMBER(3, 0) 
, NR_KONTA VARCHAR2(26 BYTE) 
, CZY_FIRMA CHAR(1 BYTE) DEFAULT 0 NOT NULL 
, CONSTRAINT KONTRAHENCI_PK PRIMARY KEY 
  (
    ID_KONTRAHENTA 
  )
  ENABLE 
);

CREATE TABLE TOWARY 
(
  ID_TOWARU NUMBER(4, 0) NOT NULL 
, NAZWA VARCHAR2(40 BYTE) NOT NULL 
, ILOSC NUMBER(5, 2) DEFAULT 0 NOT NULL 
, ID_JEDNOSTKI NUMBER(2, 0) NOT NULL 
, ID_KATEGORII NUMBER(2, 0) NOT NULL 
, CONSTRAINT TOWARY_PK PRIMARY KEY 
  (
    ID_TOWARU 
  )
  ENABLE 
);

CREATE TABLE DOSTAWY 
(
  ID_DOSTAWY NUMBER(7, 0) NOT NULL 
, DATA DATE NOT NULL 
, ID_DOSTAWCY NUMBER(5, 0) NOT NULL 
, CONSTRAINT DOSTAWY_PK PRIMARY KEY 
  (
    ID_DOSTAWY 
  )
  ENABLE 
);

CREATE TABLE FAKTURY 
(
  ID_FAKTURY NUMBER(7, 0) NOT NULL 
, NR_FAKTURY VARCHAR2(20 BYTE) NOT NULL 
, ID_NABYWCY NUMBER(5, 0) NOT NULL 
, ID_SPRZEDAWCY NUMBER(5, 0) NOT NULL 
, DATA_WYSTAWIENIA DATE NOT NULL 
, DATA_ZAPLATY DATE 
, TERMIN_ZAPLATY DATE NOT NULL 
, STAWKA_VAT NUMBER(3, 0) NOT NULL 
, SPOSOB_ZAPLATY VARCHAR2(30 BYTE) 
, NETTO NUMBER(7, 2) NOT NULL 
, VAT NUMBER(7, 2) NOT NULL 
, BRUTTO NUMBER(7, 2) NOT NULL 
, WARTOSC_KWOTY_SLOWNIE VARCHAR2(100 BYTE) NOT NULL 
, CZY_WYCHODZACA CHAR(1 BYTE) AS ( CASE "ID_NABYWCY" WHEN 1 THEN '1' ELSE '0' END ) VIRTUAL 
, CONSTRAINT FAKTURY_PK PRIMARY KEY 
  (
    ID_FAKTURY 
  )
  ENABLE 
);

CREATE TABLE ZAMOWIENIA 
(
  ID_ZAMOWIENIA NUMBER(7, 0) NOT NULL 
, DATA DATE NOT NULL 
, STATUS NUMBER(2, 0) NOT NULL 
, ID_KLIENTA NUMBER(5, 0) NOT NULL 
, CONSTRAINT ZAMOWIENIA_PK PRIMARY KEY 
  (
    ID_ZAMOWIENIA 
  )
  ENABLE 
);

CREATE TABLE DANIA_SKLADNIKI 
(
  ID_DANIA NUMBER(3, 0) NOT NULL 
, ID_TOWARU NUMBER(4, 0) NOT NULL 
, ILOSC NUMBER(4, 2) NOT NULL 
, CONSTRAINT DANIA_SKLADNIKI_PK PRIMARY KEY 
  (
    ID_DANIA 
  , ID_TOWARU 
  )
  ENABLE 
);

CREATE TABLE DOSTAWY_POZYCJE 
(
  ID_DOSTAWY NUMBER(7, 0) NOT NULL 
, ID_TOWARU NUMBER(4, 0) NOT NULL 
, ILOSC NUMBER(5, 2) NOT NULL 
, CENA_JEDNOSTKOWA NUMBER(6, 2) NOT NULL 
, SERIA VARCHAR2(30 BYTE) 
, DATA_WAZNOSCI DATE 
, CONSTRAINT DOSTAWY_POZYCJE_PK PRIMARY KEY 
  (
    ID_DOSTAWY 
  , ID_TOWARU 
  )
  ENABLE 
);

CREATE TABLE FAKTURY_POZYCJE 
(
  ID_FAKTURY NUMBER(7, 0) NOT NULL 
, NR_POZYCJI NUMBER(4, 0) NOT NULL 
, NAZWA VARCHAR2(50 BYTE) NOT NULL 
, ILOSC NUMBER(4, 0) NOT NULL 
, ID_JEDNOSTKI NUMBER(2, 0) 
, DATA_WYKONANIA DATE 
, NETTO NUMBER(6, 2) NOT NULL 
, VAT NUMBER(2, 0) NOT NULL 
, BRUTTO NUMBER(6, 2) NOT NULL 
, CONSTRAINT FAKTURY_POZYCJE_PK PRIMARY KEY 
  (
    ID_FAKTURY 
  , NR_POZYCJI 
  )
  ENABLE 
);

CREATE TABLE ZAMOWIENIA_POZYCJE 
(
  ID_ZAMOWIENIA NUMBER(7, 0) NOT NULL 
, ID_DANIA NUMBER(3, 0) NOT NULL 
, ILOSC NUMBER(3, 0) NOT NULL 
, WARTOSC NUMBER(6, 2) NOT NULL 
, CONSTRAINT ZAMOWIENIA_POZYCJE_PK PRIMARY KEY 
  (
    ID_ZAMOWIENIA 
  , ID_DANIA 
  )
  ENABLE 
);

CREATE VIEW BILANS_ZESTAWIENIE
AS SELECT
extract(YEAR FROM f.DATA_WYSTAWIENIA) ROK,
extract(MONTH FROM f.DATA_WYSTAWIENIA) MIESIAC,
SUM(CASE WHEN f.CZY_WYCHODZACA = '0' THEN f.NETTO ELSE 0 END) SUMA_NETTO_PRZYCHODOW,
SUM(CASE WHEN f.CZY_WYCHODZACA = '1' THEN f.NETTO ELSE 0 END) SUMA_NETTO_ROZCHODOW,
SUM(CASE WHEN f.CZY_WYCHODZACA = '0' THEN f.NETTO ELSE 0 END) - SUM(CASE WHEN f.CZY_WYCHODZACA = '1' THEN f.NETTO ELSE 0 END) BILANS
FROM FAKTURY f
GROUP BY extract(YEAR FROM f.DATA_WYSTAWIENIA), extract(MONTH FROM f.DATA_WYSTAWIENIA);

CREATE VIEW DANIA_ZAMOWIENIA_ZESTAWIENIE
AS SELECT
  extract(YEAR FROM z.DATA) ROK,
  extract(MONTH FROM z.DATA) MIESIAC,
  d.NAZWA DANIE,
  COUNT(z.ID_ZAMOWIENIA) LICZBA_ZAMOWIEN
  FROM DANIA d
  JOIN ZAMOWIENIA_POZYCJE zp ON (zp.ID_DANIA = d.ID_DANIA)
  JOIN ZAMOWIENIA z ON (z.ID_ZAMOWIENIA = zp.ID_ZAMOWIENIA)
  group by extract(YEAR FROM z.DATA), extract(MONTH FROM z.DATA), d.NAZWA;

CREATE VIEW KONTRAHENCI_ZAMOWIENIA_MIESIAC
AS SELECT k.ID_KONTRAHENTA ID,
  CASE WHEN k.CZY_FIRMA = '1' THEN k.NAZWA ELSE CONCAT (k.IMIE, CONCAT(' ', k.NAZWISKO)) END NAZWA, 
  COUNT(z.ID_ZAMOWIENIA) LICZBA_ZAMOWIEN,
  SUM(f.NETTO) SUMA_NETTO
  FROM KONTRAHENCI k
  JOIN ZAMOWIENIA z ON (z.ID_KLIENTA = k.ID_KONTRAHENTA)
  JOIN FAKTURY f ON (f.ID_NABYWCY = k.ID_KONTRAHENTA)
  WHERE f.DATA_WYSTAWIENIA > sysdate-30 and z.DATA > sysdate-30
  group by k.ID_KONTRAHENTA, CASE WHEN k.CZY_FIRMA = '1' THEN k.NAZWA ELSE CONCAT (k.IMIE, CONCAT(' ', k.NAZWISKO)) END;

CREATE VIEW KONTRAHENCI_ZAMOWIENIA_ZESTAWIENIE
AS SELECT
  extract(YEAR FROM f.DATA_WYSTAWIENIA) ROK,
  extract(MONTH FROM f.DATA_WYSTAWIENIA) MIESIAC,
  k.ID_KONTRAHENTA ID,
  CASE WHEN k.CZY_FIRMA = '1' THEN k.NAZWA ELSE CONCAT (k.IMIE, CONCAT(' ', k.NAZWISKO)) END NAZWA, 
  COUNT(z.ID_ZAMOWIENIA) LICZBA_ZAMOWIEN,
  SUM(f.NETTO) SUMA_NETTO
  FROM KONTRAHENCI k
  JOIN ZAMOWIENIA z ON (z.ID_KLIENTA = k.ID_KONTRAHENTA)
  JOIN FAKTURY f ON (f.ID_NABYWCY = k.ID_KONTRAHENTA)
  GROUP BY extract(YEAR FROM f.DATA_WYSTAWIENIA), extract(MONTH FROM f.DATA_WYSTAWIENIA), k.ID_KONTRAHENTA, CASE WHEN k.CZY_FIRMA = '1' THEN k.NAZWA ELSE CONCAT (k.IMIE, CONCAT(' ', k.NAZWISKO)) END;

CREATE VIEW PRZYCHODY_ZESTAWIENIE
AS SELECT
  extract(YEAR FROM f.DATA_WYSTAWIENIA) ROK,
  extract(MONTH FROM f.DATA_WYSTAWIENIA) MIESIAC,
  f.SPOSOB_ZAPLATY SPOSOB_PLATNOSCI,
  COUNT(f.ID_FAKTURY) LICZBA_FAKTUR,
  SUM(f.NETTO) SUMA_NETTO
  FROM FAKTURY f
  WHERE f.CZY_WYCHODZACA = '0'
  group by extract(YEAR FROM f.DATA_WYSTAWIENIA), extract(MONTH FROM f.DATA_WYSTAWIENIA), f.SPOSOB_ZAPLATY;

CREATE VIEW ROZCHODY_ZESTAWIENIE_PODATKI
AS SELECT
  extract(YEAR FROM f.DATA_WYSTAWIENIA) ROK,
  extract(MONTH FROM f.DATA_WYSTAWIENIA) MIESIAC,
  f.STAWKA_VAT VAT,
  COUNT(f.ID_FAKTURY) LICZBA_FAKTUR,
  SUM(f.VAT) SUMA_PODATKU
  FROM FAKTURY f
  WHERE f.CZY_WYCHODZACA = '1'
  group by extract(YEAR FROM f.DATA_WYSTAWIENIA), extract(MONTH FROM f.DATA_WYSTAWIENIA), f.STAWKA_VAT;

CREATE VIEW ROZCHODY_ZESTAWIENIE_TOWARY
AS SELECT
  extract(YEAR FROM d.DATA) ROK,
  extract(MONTH FROM d.DATA) MIESIAC,
  t.NAZWA TOWAR,
  SUM(dp.ILOSC) DOSTARCZONA_ILOSC,
  j.NAZWA JEDNOSTKA,
  SUM(dp.ILOSC) * dp.CENA_JEDNOSTKOWA KOSZT_DOSTAW
  FROM TOWARY t
  JOIN DOSTAWY_POZYCJE dp ON (dp.ID_TOWARU = t.ID_TOWARU)
  JOIN DOSTAWY d ON (d.ID_DOSTAWY = dp.ID_DOSTAWY)
  JOIN SL_JEDNOSTKI j ON (j.ID_JEDNOSTKI = t.ID_JEDNOSTKI)
  group by extract(YEAR FROM d.DATA), extract(MONTH FROM d.DATA), t.NAZWA, j.NAZWA, dp.CENA_JEDNOSTKOWA;

CREATE UNIQUE INDEX DANIA_SKLADNIKI_T_INDEX ON DANIA_SKLADNIKI (ID_TOWARU ASC);

CREATE UNIQUE INDEX DOSTAWY_DOSTAWCY_INDEX ON DOSTAWY (ID_DOSTAWCY ASC);

CREATE INDEX DOSTAWY_POZYCJE_T_INDEX ON DOSTAWY_POZYCJE (ID_TOWARU ASC);

CREATE UNIQUE INDEX FAKTURY_NABYWCY_INDEX ON FAKTURY (ID_NABYWCY ASC);

CREATE INDEX FAKTURY_SPRZEDAWCY_INDEX ON FAKTURY (ID_SPRZEDAWCY ASC);

CREATE INDEX KONTRAHENCI_BANK_INDEX ON KONTRAHENCI (ID_BANKU ASC);

CREATE UNIQUE INDEX TOWARY_JEDNOSTKI_INDEX ON TOWARY (ID_JEDNOSTKI ASC);

CREATE UNIQUE INDEX TOWARY_KATEGORIE_INDEX ON TOWARY (ID_KATEGORII ASC);

CREATE INDEX ZAMOWIENIA_KLIENCI_INDEX ON ZAMOWIENIA (ID_KLIENTA ASC);

CREATE INDEX ZAMOWIENIA_STATUSY_INDEX ON ZAMOWIENIA (STATUS ASC);

CREATE UNIQUE INDEX ZAMOWIENIA_POZYCJE_D_INDEX ON ZAMOWIENIA_POZYCJE (ID_DANIA ASC);

ALTER TABLE KONTRAHENCI
ADD CONSTRAINT KONTRAHENCI_NIP_UK UNIQUE 
(
  NIP 
)
ENABLE;

ALTER TABLE DANIA_SKLADNIKI
ADD CONSTRAINT DANIA_SKLADNIKI_DANIA_FK FOREIGN KEY
(
  ID_DANIA 
)
REFERENCES DANIA
(
  ID_DANIA 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE DANIA_SKLADNIKI
ADD CONSTRAINT DANIA_SKLADNIKI_TOWARY_FK FOREIGN KEY
(
  ID_TOWARU 
)
REFERENCES TOWARY
(
  ID_TOWARU 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE DOSTAWY
ADD CONSTRAINT DOSTAWY_DOSTAWCY_FK FOREIGN KEY
(
  ID_DOSTAWCY 
)
REFERENCES KONTRAHENCI
(
  ID_KONTRAHENTA 
)
ENABLE;

ALTER TABLE DOSTAWY_POZYCJE
ADD CONSTRAINT DOSTAWY_POZYCJE_DOSTAWY_FK FOREIGN KEY
(
  ID_DOSTAWY 
)
REFERENCES DOSTAWY
(
  ID_DOSTAWY 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE DOSTAWY_POZYCJE
ADD CONSTRAINT DOSTAWY_POZYCJE_TOWARY_FK FOREIGN KEY
(
  ID_TOWARU 
)
REFERENCES TOWARY
(
  ID_TOWARU 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE FAKTURY
ADD CONSTRAINT FAKTURY_NABYWCY_FK FOREIGN KEY
(
  ID_NABYWCY 
)
REFERENCES KONTRAHENCI
(
  ID_KONTRAHENTA 
)
ENABLE;

ALTER TABLE FAKTURY
ADD CONSTRAINT FAKTURY_SPRZEDAWCY_FK FOREIGN KEY
(
  ID_SPRZEDAWCY 
)
REFERENCES KONTRAHENCI
(
  ID_KONTRAHENTA 
)
ENABLE;

ALTER TABLE FAKTURY_POZYCJE
ADD CONSTRAINT FAKTURY_POZYCJE_F_FK FOREIGN KEY
(
  ID_FAKTURY 
)
REFERENCES FAKTURY
(
  ID_FAKTURY 
)
ENABLE;

ALTER TABLE FAKTURY_POZYCJE
ADD CONSTRAINT FAKTURY_POZYCJE_J_FK FOREIGN KEY
(
  ID_JEDNOSTKI 
)
REFERENCES SL_JEDNOSTKI
(
  ID_JEDNOSTKI 
)
ENABLE;

ALTER TABLE KONTRAHENCI
ADD CONSTRAINT KONTRAHENCI_BANK_FK FOREIGN KEY
(
  ID_BANKU 
)
REFERENCES SL_BANKI
(
  ID_BANKU 
)
ENABLE;

ALTER TABLE TOWARY
ADD CONSTRAINT TOWARY_JEDNOSTKI_FK FOREIGN KEY
(
  ID_JEDNOSTKI 
)
REFERENCES SL_JEDNOSTKI
(
  ID_JEDNOSTKI 
)
ENABLE;

ALTER TABLE TOWARY
ADD CONSTRAINT TOWARY_KATEGORIE_FK FOREIGN KEY
(
  ID_KATEGORII 
)
REFERENCES SL_KATEGORIE_PODATKOWE
(
  ID_KATEGORII 
)
ENABLE;

ALTER TABLE ZAMOWIENIA
ADD CONSTRAINT ZAMOWIENIA_KLIENCI_FK FOREIGN KEY
(
  ID_KLIENTA 
)
REFERENCES KONTRAHENCI
(
  ID_KONTRAHENTA 
)
ENABLE;

ALTER TABLE ZAMOWIENIA
ADD CONSTRAINT ZAMOWIENIA_STATUS_FK FOREIGN KEY
(
  STATUS 
)
REFERENCES SL_STATUSY_ZAMOWIEN
(
  ID_STATUSU 
)
ENABLE;

ALTER TABLE ZAMOWIENIA_POZYCJE
ADD CONSTRAINT ZAMOWIENIA_POZYCJE_DANIA_FK FOREIGN KEY
(
  ID_DANIA 
)
REFERENCES DANIA
(
  ID_DANIA 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ZAMOWIENIA_POZYCJE
ADD CONSTRAINT ZAMOWIENIA_POZYCJE_FK FOREIGN KEY
(
  ID_ZAMOWIENIA 
)
REFERENCES ZAMOWIENIA
(
  ID_ZAMOWIENIA 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE FAKTURY
ADD CONSTRAINT FAKTURY_PARTIE_CHK CHECK 
(ID_NABYWCY != ID_SPRZEDAWCY)
ENABLE;

ALTER TABLE FAKTURY
ADD CONSTRAINT FAKTURY_POWIAZANA_FIRMA_CHK CHECK 
(ID_NABYWCY = 1 OR ID_SPRZEDAWCY = 1)
ENABLE;

ALTER TABLE KONTRAHENCI
ADD CONSTRAINT KONTRAHENCI_CZY_FIRMA_CHK CHECK 
(CZY_FIRMA IN ('0', '1'))
ENABLE;

COMMENT ON TABLE SL_JEDNOSTKI IS 'Tabela slownikowa z dostepnymi jednostkami, w ktorych wyrazone moga byc produkty.';

COMMENT ON TABLE SL_KATEGORIE_PODATKOWE IS 'Tabela slownikowa z kategoriami produktow spozywczych';
