SET SQLBLANKLINES ON
CREATE TABLE DANIA 
(
  ID_DANIA NUMBER(3, 0) NOT NULL 
, NAZWA VARCHAR2(30) NOT NULL 
, OPIS VARCHAR2(200) 
, CENA NUMBER(5, 2) NOT NULL 
, DOSTEPNOSC NUMBER(3, 0) DEFAULT 0 NOT NULL 
, CONSTRAINT DANIA_PK PRIMARY KEY 
  (
    ID_DANIA 
  )
  ENABLE 
);

CREATE TABLE SL_BANKI 
(
  ID_BANKU NUMBER(3, 0) NOT NULL 
, NAZWA VARCHAR2(50) NOT NULL 
, CONSTRAINT SL_BANKI_PK PRIMARY KEY 
  (
    ID_BANKU 
  )
  ENABLE 
) 
ORGANIZATION INDEX;

CREATE TABLE SL_JEDNOSTKI 
(
  ID_JEDNOSTKI NUMBER(2, 0) NOT NULL 
, NAZWA VARCHAR2(30) NOT NULL 
, SKROT VARCHAR2(10) NOT NULL 
, CONSTRAINT SL_JEDNOSTKI_PK PRIMARY KEY 
  (
    ID_JEDNOSTKI 
  )
  ENABLE 
) 
ORGANIZATION INDEX;

CREATE TABLE SL_KATEGORIE_PODATKOWE 
(
  ID_KATEGORII NUMBER(2, 0) NOT NULL 
, NAZWA VARCHAR2(30) NOT NULL 
, OPODATKOWANIE NUMBER(2, 0) NOT NULL 
, CONSTRAINT SL_KATEGORIE_PK PRIMARY KEY 
  (
    ID_KATEGORII 
  )
  ENABLE 
) 
ORGANIZATION INDEX;

CREATE TABLE SL_STATUSY_ZAMOWIEN 
(
  ID_STATUSU NUMBER(2, 0) NOT NULL 
, NAZWA VARCHAR2(20) NOT NULL 
, CONSTRAINT SL_STATUSY_ZAMOWIEN_PK PRIMARY KEY 
  (
    ID_STATUSU 
  )
  ENABLE 
) 
ORGANIZATION INDEX;

CREATE TABLE KONTRAHENCI 
(
  ID_KONTRAHENTA NUMBER(5, 0) NOT NULL 
, IMIE VARCHAR2(20) 
, NAZWISKO VARCHAR2(40) 
, NAZWA VARCHAR2(50) 
, NIP CHAR(13) 
, MAIL VARCHAR2(40) NOT NULL 
, ADRES VARCHAR2(150) NOT NULL 
, TELEFON VARCHAR2(15) NOT NULL 
, ID_BANKU NUMBER(3, 0) 
, NR_KONTA VARCHAR2(26) 
, CZY_FIRMA CHAR(1) DEFAULT 0 NOT NULL 
, CONSTRAINT KONTRAHENCI_PK PRIMARY KEY 
  (
    ID_KONTRAHENTA 
  )
  ENABLE 
);

CREATE TABLE TOWARY 
(
  ID_TOWARU NUMBER(4, 0) NOT NULL 
, NAZWA VARCHAR2(40) NOT NULL 
, ILOSC NUMBER(5, 2) DEFAULT 0 NOT NULL 
, ID_JEDNOSTKI NUMBER(2, 0) NOT NULL 
, ID_KATEGORII NUMBER(2, 0) NOT NULL 
, CONSTRAINT TOWARY_PK PRIMARY KEY 
  (
    ID_TOWARU 
  )
  ENABLE 
);

CREATE TABLE DOSTAWY 
(
  ID_DOSTAWY NUMBER(7, 0) NOT NULL 
, DATA DATE NOT NULL 
, ID_DOSTAWCY NUMBER(5, 0) NOT NULL 
, CONSTRAINT DOSTAWY_PK PRIMARY KEY 
  (
    ID_DOSTAWY 
  )
  ENABLE 
);

CREATE TABLE FAKTURY 
(
  ID_FAKTURY NUMBER(7, 0) NOT NULL 
, NR_FAKTURY VARCHAR2(20) NOT NULL 
, ID_NABYWCY NUMBER(5, 0) NOT NULL 
, ID_SPRZEDAWCY NUMBER(5, 0) NOT NULL 
, DATA_WYSTAWIENIA DATE NOT NULL 
, DATA_ZAPLATY DATE 
, TERMIN_ZAPLATY DATE NOT NULL 
, STAWKA_VAT NUMBER(3, 0) NOT NULL 
, SPOSOB_ZAPLATY VARCHAR2(30) 
, NETTO NUMBER(7, 2) NOT NULL 
, VAT NUMBER(7, 2) NOT NULL 
, BRUTTO NUMBER(7, 2) NOT NULL 
, WARTOSC_KWOTY_SLOWNIE VARCHAR2(100) NOT NULL
, CZY_WYCHODZACA CHAR(1) GENERATED ALWAYS AS (CASE WHEN ID_NABYWCY = 1 THEN '1' ELSE '0' END)
, CONSTRAINT FAKTURY_PK PRIMARY KEY 
  (
    ID_FAKTURY 
  )
  ENABLE 
);

CREATE TABLE ZAMOWIENIA 
(
  ID_ZAMOWIENIA NUMBER(7, 0) NOT NULL 
, DATA DATE NOT NULL 
, STATUS NUMBER(2, 0) NOT NULL 
, ID_KLIENTA NUMBER(5, 0) NOT NULL 
, CONSTRAINT ZAMOWIENIA_PK PRIMARY KEY 
  (
    ID_ZAMOWIENIA 
  )
  ENABLE 
);

CREATE TABLE DANIA_SKLADNIKI 
(
  ID_DANIA NUMBER(3, 0) NOT NULL 
, ID_TOWARU NUMBER(4, 0) NOT NULL 
, ILOSC NUMBER(4, 2) NOT NULL 
, CONSTRAINT DANIA_SKLADNIKI_PK PRIMARY KEY 
  (
    ID_DANIA 
  , ID_TOWARU 
  )
  ENABLE 
);

CREATE TABLE DOSTAWY_POZYCJE 
(
  ID_DOSTAWY NUMBER(7, 0) NOT NULL 
, ID_TOWARU NUMBER(4, 0) NOT NULL 
, ILOSC NUMBER(5, 2) NOT NULL 
, CENA_JEDNOSTKOWA NUMBER(6, 2) NOT NULL 
, SERIA VARCHAR2(30) 
, DATA_WAZNOSCI DATE 
, CONSTRAINT DOSTAWY_POZYCJE_PK PRIMARY KEY 
  (
    ID_DOSTAWY 
  , ID_TOWARU 
  )
  ENABLE 
);

CREATE TABLE FAKTURY_POZYCJE 
(
  ID_FAKTURY NUMBER(7, 0) NOT NULL 
, NR_POZYCJI NUMBER(4, 0) NOT NULL 
, NAZWA VARCHAR2(50) NOT NULL 
, ILOSC NUMBER(4, 0) NOT NULL 
, ID_JEDNOSTKI NUMBER(2, 0) 
, DATA_WYKONANIA DATE 
, NETTO NUMBER(6, 2) NOT NULL 
, VAT NUMBER(2, 0) NOT NULL 
, BRUTTO NUMBER(6, 2) NOT NULL 
, CONSTRAINT FAKTURY_POZYCJE_PK PRIMARY KEY 
  (
    ID_FAKTURY 
  , NR_POZYCJI 
  )
  ENABLE 
);

CREATE TABLE ZAMOWIENIA_POZYCJE 
(
  ID_ZAMOWIENIA NUMBER(7, 0) NOT NULL 
, ID_DANIA NUMBER(3, 0) NOT NULL 
, ILOSC NUMBER(3, 0) NOT NULL 
, WARTOSC NUMBER(6, 2) NOT NULL 
, CONSTRAINT ZAMOWIENIA_POZYCJE_PK PRIMARY KEY 
  (
    ID_ZAMOWIENIA 
  , ID_DANIA 
  )
  ENABLE 
);

CREATE UNIQUE INDEX DANIA_SKLADNIKI_T_INDEX ON DANIA_SKLADNIKI (ID_TOWARU ASC);

CREATE UNIQUE INDEX DOSTAWY_DOSTAWCY_INDEX ON DOSTAWY (ID_DOSTAWCY ASC);

CREATE INDEX DOSTAWY_POZYCJE_T_INDEX ON DOSTAWY_POZYCJE (ID_TOWARU ASC);

CREATE UNIQUE INDEX FAKTURY_NABYWCY_INDEX ON FAKTURY (ID_NABYWCY ASC);

CREATE INDEX FAKTURY_SPRZEDAWCY_INDEX ON FAKTURY (ID_SPRZEDAWCY ASC);

CREATE INDEX KONTRAHENCI_BANK_INDEX ON KONTRAHENCI (ID_BANKU ASC);

CREATE UNIQUE INDEX TOWARY_JEDNOSTKI_INDEX ON TOWARY (ID_JEDNOSTKI ASC);

CREATE UNIQUE INDEX TOWARY_KATEGORIE_INDEX ON TOWARY (ID_KATEGORII ASC);

CREATE INDEX ZAMOWIENIA_KLIENCI_INDEX ON ZAMOWIENIA (ID_KLIENTA ASC);

CREATE INDEX ZAMOWIENIA_STATUSY_INDEX ON ZAMOWIENIA (STATUS ASC);

CREATE UNIQUE INDEX ZAMOWIENIA_POZYCJE_D_INDEX ON ZAMOWIENIA_POZYCJE (ID_DANIA ASC);

ALTER TABLE KONTRAHENCI
ADD CONSTRAINT KONTRAHENCI_NIP_UK UNIQUE 
(
  NIP 
)
ENABLE;

ALTER TABLE DANIA_SKLADNIKI
ADD CONSTRAINT DANIA_SKLADNIKI_DANIA_FK FOREIGN KEY
(
  ID_DANIA 
)
REFERENCES DANIA
(
  ID_DANIA 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE DANIA_SKLADNIKI
ADD CONSTRAINT DANIA_SKLADNIKI_TOWARY_FK FOREIGN KEY
(
  ID_TOWARU 
)
REFERENCES TOWARY
(
  ID_TOWARU 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE DOSTAWY
ADD CONSTRAINT DOSTAWY_DOSTAWCY_FK FOREIGN KEY
(
  ID_DOSTAWCY 
)
REFERENCES KONTRAHENCI
(
  ID_KONTRAHENTA 
)
ENABLE;

ALTER TABLE DOSTAWY_POZYCJE
ADD CONSTRAINT DOSTAWY_POZYCJE_DOSTAWY_FK FOREIGN KEY
(
  ID_DOSTAWY 
)
REFERENCES DOSTAWY
(
  ID_DOSTAWY 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE DOSTAWY_POZYCJE
ADD CONSTRAINT DOSTAWY_POZYCJE_TOWARY_FK FOREIGN KEY
(
  ID_TOWARU 
)
REFERENCES TOWARY
(
  ID_TOWARU 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE FAKTURY
ADD CONSTRAINT FAKTURY_NABYWCY_FK FOREIGN KEY
(
  ID_NABYWCY 
)
REFERENCES KONTRAHENCI
(
  ID_KONTRAHENTA 
)
ENABLE;

ALTER TABLE FAKTURY
ADD CONSTRAINT FAKTURY_SPRZEDAWCY_FK FOREIGN KEY
(
  ID_SPRZEDAWCY 
)
REFERENCES KONTRAHENCI
(
  ID_KONTRAHENTA 
)
ENABLE;

ALTER TABLE FAKTURY_POZYCJE
ADD CONSTRAINT FAKTURY_POZYCJE_F_FK FOREIGN KEY
(
  ID_FAKTURY 
)
REFERENCES FAKTURY
(
  ID_FAKTURY 
)
ENABLE;

ALTER TABLE FAKTURY_POZYCJE
ADD CONSTRAINT FAKTURY_POZYCJE_J_FK FOREIGN KEY
(
  ID_JEDNOSTKI 
)
REFERENCES SL_JEDNOSTKI
(
  ID_JEDNOSTKI 
)
ENABLE;

ALTER TABLE KONTRAHENCI
ADD CONSTRAINT KONTRAHENCI_BANK_FK FOREIGN KEY
(
  ID_BANKU 
)
REFERENCES SL_BANKI
(
  ID_BANKU 
)
ENABLE;

ALTER TABLE TOWARY
ADD CONSTRAINT TOWARY_JEDNOSTKI_FK FOREIGN KEY
(
  ID_JEDNOSTKI 
)
REFERENCES SL_JEDNOSTKI
(
  ID_JEDNOSTKI 
)
ENABLE;

ALTER TABLE TOWARY
ADD CONSTRAINT TOWARY_KATEGORIE_FK FOREIGN KEY
(
  ID_KATEGORII 
)
REFERENCES SL_KATEGORIE_PODATKOWE
(
  ID_KATEGORII 
)
ENABLE;

ALTER TABLE ZAMOWIENIA
ADD CONSTRAINT ZAMOWIENIA_KLIENCI_FK FOREIGN KEY
(
  ID_KLIENTA 
)
REFERENCES KONTRAHENCI
(
  ID_KONTRAHENTA 
)
ENABLE;

ALTER TABLE ZAMOWIENIA
ADD CONSTRAINT ZAMOWIENIA_STATUS_FK FOREIGN KEY
(
  STATUS 
)
REFERENCES SL_STATUSY_ZAMOWIEN
(
  ID_STATUSU 
)
ENABLE;

ALTER TABLE ZAMOWIENIA_POZYCJE
ADD CONSTRAINT ZAMOWIENIA_POZYCJE_DANIA_FK FOREIGN KEY
(
  ID_DANIA 
)
REFERENCES DANIA
(
  ID_DANIA 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE ZAMOWIENIA_POZYCJE
ADD CONSTRAINT ZAMOWIENIA_POZYCJE_FK FOREIGN KEY
(
  ID_ZAMOWIENIA 
)
REFERENCES ZAMOWIENIA
(
  ID_ZAMOWIENIA 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE FAKTURY
ADD CONSTRAINT FAKTURY_PARTIE_CHK CHECK 
(ID_NABYWCY != ID_SPRZEDAWCY)
ENABLE;

ALTER TABLE KONTRAHENCI
ADD CONSTRAINT KONTRAHENCI_CZY_FIRMA_CHK CHECK 
(CZY_FIRMA IN ('0', '1'))
ENABLE;

COMMENT ON TABLE SL_JEDNOSTKI IS 'Tabela slownikowa z dostepnymi jednostkami, w ktorych wyrazone moga byc produkty.';

COMMENT ON TABLE SL_KATEGORIE_PODATKOWE IS 'Tabela slownikowa z kategoriami produktow spozywczych';
